Update uwhackweeks hub
2i2c-org/infrastructure pull request #1006
Opened 2022-02-17 13:13 UTC by GeorgianaElena

- This updates uwhackwweks `funded_by` section as noticed by @damianavila [here](https://github.com/2i2c-org/infrastructure/pull/981#discussion_r808598988)
- Changes the helm chart used by the hub to `basehub` instead of `daskhub` (see [this comment](https://github.com/2i2c-org/infrastructure/issues/998#issuecomment-1041818555) for context)
_Note: Not sure about this last one. Waiting for confirmation if the uwhackweeks hub wasn't meant to be a daskhub as it's my understanding from the initial issue_

2022-02-17 15:10 UTC, damianavila approved these changes
LGTM (modulo the base hub is confirmed, otherwise the URL change LGTM).

2022-02-19 15:00 UTC, damianavila commented
> Changing daskhub to basehub is a bit of a destructive change, as you're modifying what chart will be installed. I am reasonably convinced it'll just fail, and if not produce some inconsistent state.

Mmm... that is a good point given that the hub is already running and ready to work, AFAIK from #962.
But at the same time, it itches me a little bit that we are deploying resources we are not going to use.
This happened as well with openscapes...
I guess we should improve our process in the gathering of information from the community representative so we do not repeat ourselves on this sort of error.

2022-02-19 15:01 UTC, damianavila requested changes
Let's keep the daskhub since changing to basehub could be a destructive action.

2022-02-21 08:30 UTC, GeorgianaElena commented
Thanks everyone for the feedback! I've dropped the commit that changed the template type and plan to merge this soon!

So, if we ever want to change the type of a running hub (basehub/daskhub), we first need to tear it down, and just deploy a new one with the desired base chart, right?

2022-02-21 08:33 UTC, merged

2022-02-22 00:25 UTC, damianavila commented
> So, if we ever want to change the type of a running hub (basehub/daskhub), we first need to tear it down, and just deploy a new one with the desired base chart, right?

That seems to be a reasonable recommendation (modulo you migrate the user content from the old daskhub to the new base hub, I guess).

2022-02-22 08:54 UTC, sgibson91 commented
> modulo you migrate the user content from the old daskhub to the new base hub, I guess

If we're redeploying into the same cluster (which I think in most cases we would be) I _think_ we would only need to migrate the hub database, and then it should reuse the NFS storage automatically