Fix typo causing openscapes users to be under resourced
2i2c-org/infrastructure pull request #2225
Opened 2023-02-17 18:42 UTC by yuvipanda

Without the G, we were only guaranteeing them these values in bytes!

2023-02-17 19:00 UTC, pnasrat approved these changes
LGTM

Also who needs more than 0.969 bytes anyway

2023-02-17 19:23 UTC, consideRatio commented
Ah :) I've realized this and cordoned nodes to ensure they are not running out of capacity.

There is also a need for this fix on linked-earth's hub. Let's not merge it before the event they have right now is over!

2023-02-17 19:26 UTC, yuvipanda commented
@consideRatio i've already deployed this - they reached out to me on the openscapes slack (i am involved there in a few different capacities), as their servers were all slow right now! Deploying this fixed it. I'm going to merge this now so it doesn't get undone by another deploy.

Can I leave the linked-earth fix to you? :D

2023-02-17 19:26 UTC, merged

2023-02-17 19:26 UTC, consideRatio requested changes
@yuvipanda the thing I want fixed is addition of a G, but not a change in cpu-guarantee. I've not yet documented this, but its intentional!

2023-02-17 19:28 UTC, consideRatio commented
I cancelled this workflow to avoid a hub restart during their event!

I'll fix things and can clarify why i want a systematic 10th of the actual CPU designated for the user and such as part of piloting node sharing later.

2023-02-17 19:30 UTC, yuvipanda commented
@consideRatio I'd love to read that! Nobody was getting 16 CPUs anywhere and everyone (including me) was pretty confused, and stuff was running way slower than they expected. Sorry if that happened in another PR and I missed that.

I also don't think the hub would have restarted in this case, as this would've been a no-op deploy.

2023-02-17 19:39 UTC, consideRatio commented
> Nobody was getting 16 CPUs anywhere and everyone (including me) was pretty confused, and stuff was running way slower than they expected. 

Yikes is things running slower than expected? My understanding is that they are ~30 users on 64 CPU nodes, and should be able to go to 64 cores if other users idle, but if they all go full throttle should get 2 each by having the same cpu-share configured via requests.

Are they speaking to you from another channel besides support tickets?

2023-02-17 19:41 UTC, yuvipanda commented
@consideRatio unfortunately yes, this was on the openscapes slack. The issue seems to be that the description says '16 CPUs' but then the guarantee was for 1.6 CPUs only. I didn't want to bounce them to the support channel at that time as this was happening while a presentation was going on and the presenter was struggling with speed. I'll chat about that once their event is over. I'll also share those messages with you on slack.

2023-02-17 19:45 UTC, consideRatio commented
> The issue seems to be that the description says '16 CPUs' but then the guarantee was for 1.6 CPUs only

If they pick something with 16 CPU guarantee, they should not arrive at a node being outcompeted to use less than 16 CPU by anything else in the current setup.

2023-02-17 19:46 UTC, yuvipanda commented
ok i'm super confused, especially as I see no limits. I'll just wait for a longer explanation later! :)

2023-02-17 19:55 UTC, consideRatio commented
You get little CPU if you are limited, or if you fail to compete against other containers with a cpu share far higher than yourself. That is my understanding. Without limit, the only way they would be slow CPU wise would be for being outcompeted - which they won't be if all users have the same reduction of CPU capacity.

I'll try to verify my understanding later, but for now I'll head off work!

2023-02-17 19:57 UTC, consideRatio commented
https://kubernetes.io/docs/tasks/configure-pod-container/assign-cpu-resource/#if-you-do-not-specify-a-cpu-limit

Maybe there was a automatic limit assigned? Argh I can't pull away so easily from a mystery but I have to for now.

Thanks for helping openscapes people out Yuvi!

2023-02-18 13:31 UTC, consideRatio commented
I did an investigation in #2228, and I don't think for example `distributed` would be negatively impacted by a low cpu request, as it doesn't seem to consider it - but only the nodes capacity and possible cpu limits.

I don't know what software was used, but its technically possible that software could self-hamper itself based on cpu requests rather than the node's capacity or cpu limits. I suspect most software won't do that though.