Make LEAP dask workers be not pre-emptible
2i2c-org/infrastructure pull request #2419
Opened 2023-03-24 12:43 UTC by yuvipanda

Possible way to reduce confounding factors for
https://github.com/2i2c-org/infrastructure/issues/2396

2023-03-24 12:50 UTC, consideRatio approved these changes
LGTM!

Can you add a comment to the leap.tfvars about deviating from the default of `preemptible: true` to `false` for leap? I think its good if this intentional workaround stands out

2023-03-24 12:51 UTC, pnasrat requested changes
minor documentation nit will approve once fixed

2023-03-24 12:51 UTC, pnasrat commented on terraform/gcp/projects/leap.tfvars
> +    preemptible: false,
Can you add a comment linking back to the logic for this change

2023-03-24 12:52 UTC, pnasrat commented on terraform/gcp/projects/leap.tfvars
> +    preemptible: false,
oh I see @consideRatio and I collided on this review with same feedback!

2023-03-24 12:57 UTC, consideRatio commented
Btw they may very well need a cloud quota increase for on-demand CPU now. pre-emptible/spot CPU quotas are separate from on-demand I believe, so they may run out on on-demand now that its the only kind of CPU used.

2023-03-27 09:09 UTC, yuvipanda commented
Am also going to wait for the LEAP credits issue to be resolved before deploying this.

2023-03-29 15:39 UTC, yuvipanda commented
Leap credits are done now

2023-03-29 16:08 UTC, pnasrat approved these changes
lgtm

2023-03-29 16:11 UTC, merged