Add climatematch academy hub
2i2c-org/infrastructure pull request #2599
Opened 2023-06-01 17:49 UTC by yuvipanda

- Add ability to setup resource labels for nodepools, to allow us to try tracking cloud costs on a per nodepool basis in the future (https://cloud.google.com/resource-manager/docs/creating-managing-labels). Changing these requires recreating the nodepool, so setting it now.
- Allow adding taints to nodepools, so we can properly dedicate a particular nodepool to a particular hub. Given this hub is expected to get a few thousand users, this is useful.
- Put climatematch on its own nodepool, but keep it small as the event is not expected to start until July 17.

Ref https://github.com/2i2c-org/infrastructure/issues/2524

2023-06-01 18:02 UTC, pnasrat requested changes
Generally looks good

Do we need to add docs for the tainting as it's in our own terraform code

One minor whitespace thing and one suggestion for more future proof generation of the dedicated pools rather than listing per hub in a shared cluster - though if you want to tackle that later that's fine

2023-06-01 18:06 UTC, yuvipanda commented on terraform/gcp/projects/pilot-hubs.tfvars
> +  "climatematch": {
Can you expand a little more on what this means? Would we read cluster.yaml in our terraform and apply that?

2023-06-01 18:06 UTC, yuvipanda commented on terraform/gcp/cluster.tf
> +  for_each       = var.k8s_version_prefixes
Ah, hmm - this was terraform autoformatter doing its thing - but I don't know if we have that in our pre-commit?

2023-06-01 18:15 UTC, pnasrat commented on terraform/gcp/projects/pilot-hubs.tfvars
> +  "climatematch": {
Sure. We already do this sort  of thing in uptime_checks terraform (and I assumed we used that pattern in the cluster setup)

https://github.com/2i2c-org/infrastructure/blob/master/terraform/uptime-checks/checks.tf#L4

Perhaps it's not worth it until the 2nd or 3rd time we add a dedicated node pool to the shared cluster.

2023-06-01 18:46 UTC, pnasrat commented on terraform/gcp/projects/pilot-hubs.tfvars
> +  "climatematch": {
That makes sense re single source, ignore this part of my review

2023-06-01 19:25 UTC, yuvipanda commented on terraform/gcp/cluster.tf
> +  for_each       = var.k8s_version_prefixes
@pnasrat I opened https://github.com/2i2c-org/infrastructure/pull/2606 adding terraform autoformat to this!

2023-06-01 19:26 UTC, yuvipanda commented on terraform/gcp/cluster.tf
> +  for_each       = var.k8s_version_prefixes
```suggestion
  for_each = var.k8s_version_prefixes
```

2023-06-01 19:26 UTC, yuvipanda commented on terraform/gcp/cluster.tf
> +  for_each       = var.k8s_version_prefixes
And removed this line of change from this PR

2023-06-05 15:49 UTC, pnasrat approved these changes
lgtm

2023-06-05 15:49 UTC, pnasrat commented on docs/howto/features/dedicated-nodepool.md
Thanks for adding the docs

2023-06-05 15:54 UTC, merged