Add an efficient, user homedirectory size prometheus reporter
2i2c-org/infrastructure pull request #2621
Opened 2023-06-06 17:13 UTC by yuvipanda

This deploys https://github.com/yuvipanda/prometheus-dirsize-exporter, an *efficient* per-user homedirectory stats (size, no. of files, last modified date, etc) collector. It is capped at performing no more than 250 IO operations per second, to not overwhelm NFS servers. Metrics are refreshed every 2h after completion, although on large servers (like LEAP), they can take many many hours to complete with just 250 IO operations per second. This is perfectly fine though, as we do not need 'up to date' information. Trading off metric latency for minimal resource usage is pretty good here.

Ref https://github.com/2i2c-org/infrastructure/issues/764

2023-06-06 17:14 UTC, yuvipanda commented
Experimental grafana dashboard on LEAP cluster:

<img width="1728" alt="image" src="https://github.com/2i2c-org/infrastructure/assets/30430/5a8bb47f-c7ae-4421-a34e-96c94e682626">

Lookin good.

As it churns through this, it is being CPU limited at the 0.05 we have given it, which seems alright with me.

2023-06-06 17:22 UTC, pnasrat requested changes
Could you add an entry say in the support section of the infra docs on where to look for these dashboards

Maybe expanding the below 

https://infrastructure.2i2c.org/sre-guide/support/home-dir/

2023-06-06 17:55 UTC, yuvipanda commented
@pnasrat the graph panel doesn't exist yet, I just made a PR to add it: https://github.com/jupyterhub/grafana-dashboards/pull/80.

I'll add some docs too.

2023-06-12 07:09 UTC, yuvipanda commented
@pnasrat given the situation with utoronto and q planning, I won't be able to write docs this week. Are you ok with me merging this now so it can start collecting data, and I'll work on docs before end of the month?

2023-06-12 10:45 UTC, pnasrat commented
As an async team documentation for new services including operational procedures (eg how to turn off)  is necessary to ensure the team can both use and troubleshoot new services

If you want to merge without docs, please add a specific feature flag enabled and test in a single staging hub cluster to prove it out rather than turn on everywhere

2023-06-12 11:29 UTC, yuvipanda commented
Alright, I'll just mark this as draft and let this be until I have time to come back to it.

2023-06-20 02:42 UTC, yuvipanda commented
I think the right place for documenting this is upstream, so I've finally opened https://github.com/jupyterhub/grafana-dashboards/pull/84 to setup an actual docs site for the grafana dashboard. Once that's merged, I'll add a page documenting this panel.

2023-06-20 22:38 UTC, yuvipanda commented
I've added documentation about this graph to https://github.com/jupyterhub/grafana-dashboards/pull/84, so I think this is ready for review again.

2023-07-07 11:33 UTC, pnasrat approved these changes
LGTM

Can you make sure you announce this on the engineering channel so folks know there is a new component and graph they might find useful

2023-07-07 16:47 UTC, yuvipanda commented
Thanks @pnasrat, and will do once I confirm data is coming in!

2023-07-07 16:47 UTC, merged