2i2c-aws-us, showcase: Add 2i2c-community-showcase:access-2i2c-showcase to allowed orgs
2i2c-org/infrastructure pull request #3700
Opened 2024-02-05 14:03 UTC by jnywong

Update access to the Showcase Hub using the [2i2c-community-showcase](https://github.com/orgs/2i2c-community-showcase/teams/access-2i2c-showcase) org.

- Owners of this org can invite Hub Admins to the `access-2i2c-showcase` team with maintainer rights
- Owners of this org can invite hub community users/test users as general members of the org (but not members of the `access-2i2c-showcase` team in the first instance)
- Hub Admins can **then** add community users/test users to the `access-2i2c-showcase` team using their maintainer rights to _practise_ granting access to the Showcase Hub as part of their hub champion training

@jmunroe can you double-check that this is the expected procedure before approving this request? Also, do we need to update existing access for:

- `2i2c-org:research-delight-team`?
- `2i2c-demo-hub-access:showcase-topst`?
- `ScienceCore`?

2024-02-06 09:54 UTC, jnywong commented
Related issue https://github.com/2i2c-org/community-showcase/issues/66

2024-02-06 11:34 UTC, consideRatio requested changes
This change makes users able to login to the hub, but there are restrictions on what server options users are presented with configured under `profileList` and `allowed_teams` for this hub though.

Due to that, adding the permission to login isn't sufficient for this PR I think. Revise the `allowed_teams` entries for each profileList entry as seen below:
![image](https://github.com/2i2c-org/infrastructure/assets/3837114/79eb87ab-936b-4b1e-9795-d5a08b5e4fd7)

2024-02-06 11:48 UTC, jnywong commented
Thanks for throwing your eyes on this one @consideRatio

2024-02-06 11:54 UTC, jnywong commented
Putting this in draft mode pending feedback from @jmunroe

2024-02-08 15:21 UTC, jmunroe approved these changes
lgtm!

2024-02-08 15:42 UTC, merged