basehub: reduce hub.loadRoles and clarify the situation
2i2c-org/infrastructure pull request #4030
Opened 2024-05-07 08:29 UTC by consideRatio

2024-05-07 17:02 UTC, yuvipanda requested changes
Can merge once comment is addressed.

2024-05-07 17:02 UTC, yuvipanda commented on helm-charts/basehub/values.yaml
> +    # hub.loadRoles is z2jh native config to enable configuration of
yay that it has no effect and we can remove it.

I'd suggest we just simply fully remove it, and not actually have this large comment here. It adds additional things that must be kept up to date whenever things elsewhere change, and makes this already large file even larger. Let's just remove that?

2024-05-07 17:03 UTC, yuvipanda commented on helm-charts/basehub/values.yaml
> +    #   ref: https://github.com/dask/dask-gateway/issues/829
https://github.com/2i2c-org/infrastructure/issues/4014 is the right place for this and i see you've already put it there!

2024-05-08 07:13 UTC, consideRatio commented
Thank you for reviewing @yuvipanda!

I've tested as non-admin on imagebuilding-demo as well which worked ok

2024-05-08 07:14 UTC, merged