Document the Dummy Authenticator
2i2c-org/infrastructure pull request #4103
Opened 2024-05-21 10:42 UTC by sgibson91

- fixes #4081

2024-05-21 11:34 UTC, consideRatio commented on docs/hub-deployment-guide/configure-auth/dummy-auth.md
> +```
I think so too

2024-05-21 17:40 UTC, yuvipanda requested changes
Thanks @sgibson91! I've left some comments here.

2024-05-21 17:40 UTC, yuvipanda commented on docs/hub-deployment-guide/configure-auth/dummy-auth.md
> +# Dummy Authentication
Let's call this 'shared password authentication', and keep 'Dummy authenticator' as an implementation detail. We should not set this up without a shared password.

2024-05-21 17:40 UTC, yuvipanda commented on docs/hub-deployment-guide/configure-auth/dummy-auth.md
> +We strongly recommend using a global password with the authenticator.
In our infrastructure, we should *only* support this with a global password. For fully password-less access, there is documentation under 'ephemeral hub' that uses tmpauthenticator i think.

2024-05-21 17:40 UTC, yuvipanda commented on docs/hub-deployment-guide/configure-auth/dummy-auth.md
> +```
Let's remove this, to not support this option.

2024-05-21 17:40 UTC, yuvipanda commented on docs/hub-deployment-guide/configure-auth/dummy-auth.md
> +If the community wishes to change the global password, they should do so by [submitting a ticket the support team](https://docs.2i2c.org/support/) and using `age` to encrypt the new password.
For this specific case, I think it's ok to not ask them to encrypt the password with `age`.

2024-05-22 09:03 UTC, sgibson91 commented
Thank @yuvipanda - feedback addressed in the two most recent commits

2024-05-22 22:45 UTC, yuvipanda approved these changes

2024-05-22 22:45 UTC, merged